export const GET_ORDERING_DATA = 'Orderings/GET_ORDERING_DATA';
export const SET_ORDERING_DATA = 'Orderings/SET_ORDERING_DATA';
export const GET_ORDERING_DETAIL_DATA = 'Orderings/GET_ORDERING_DETAIL_DATA';
export const SET_ORDERING_DETAIL_DATA = 'Orderings/SET_ORDERING_DETAIL_DATA';
export const UPDATE_ORDERING_STATUS = 'Orderings/UPDATE_ORDERING_STATUS';
